version: "3.9"

services:
  app:
    container_name: movie_review_predictor
    image: movie_review_predictor
    build: .
    ports:
      - "8000:8000"   # Uvicorn
      - "11434:11434" # Ollama
    volumes:
      - ollama_models:/root/.ollama

volumes:
  ollama_models:
